language: java

before_cache:
  - for lockFile in $(find ~/.gradle -name "*.lock");
    do sudo rm -rf $lockFile;
    done

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

addons:
  apt:
    packages:
      - bash

script: ./gradlew clean build

after_failure:
  - ./gradlew clean check --debug

#after_success:
#  - bash gradlew jacocoTestReport coveralls